version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/app/node_modules'
      - '.:/app'
    ports:
      - 3000:3000
